apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: item-pub-sub
spec:
  topic: items
  routes:
    default: /item
  pubsubname: item-pub-sub
scopes:
  - catalog-service
  - stock-service